Bugfix/84 uda server ssl authenticate (#87)
* changing exit code to 0 for help function of CLI tool and adding extra catch block for unknown_option errors instead of uncaught bad_any_cast exceptions being thrown for these

* simplifying help logic in cli

* adding common routines for checking if env var options are truthy

* adding tests for uda_env_options and checking in CI that SSL env var updates work as expected

* adding CI test execution for bugfix branches

* unsetting bash -e in CI step where we expect test failure

* reinstating nonzero exit codes for failing (single, non-batch) requests in uda_cli

* adding CI test for upated CLI exit codes

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -7,6 +7,7 @@ on:
       - develop
       - 'feature/**'
       - 'release/**'
+      - 'bugfix/**'
   pull_request:
     branches:
       - main
@@ -86,6 +87,7 @@ jobs:
           git
           boost
           openssl
+          cmake
           pkg-config
           libxml2
           spdlog
@@ -208,32 +210,40 @@ jobs:
         if: matrix.os == 'ubuntu-22.04' && matrix.ssl == 'OFF'
         run: >
           sudo cp /usr/local/etc/uda.socket /usr/local/etc/uda@.service /etc/systemd/system &&
+          sudo chown -R $USER:$USER /usr/local/etc &&
+          echo "export UDA_SERVER_SSL_AUTHENTICATE=OFF" >> /usr/local/etc/udaserver.cfg &&
           sudo systemctl start uda.socket &&
           sudo systemctl enable uda.socket &&
-          sudo chown -R $USER:$USER /usr/local/etc &&
           nc -4zv localhost 56565 &&
           export UDA_HOST=localhost &&
           export UDA_PORT=56565 &&
-          ./build/test/plugins/plugin_test_testplugin
+          ./build/test/plugins/plugin_test_testplugin &&
+          ctest -V --test-dir build/test/unit_tests --output-on-failure &&
+          uda_cli --help && uda_cli --request "help::help()"
 
       - name: Run SSL system tests
         if: matrix.os == 'ubuntu-22.04' && matrix.ssl == 'ON'
-        run: >
-          sudo cp /usr/local/etc/uda.socket /usr/local/etc/uda@.service /etc/systemd/system &&
-          sudo chown -R $USER:$USER /usr/local/etc &&
-          echo "export UDAHOSTNAME=github-ci-ssl" >> /usr/local/etc/udaserver.cfg &&
-          ./scripts/create_certs.sh &&
-          mkdir /usr/local/etc/certs &&
-          cp rootCA.crt server.crt server.key /usr/local/etc/certs &&
-          sudo systemctl start uda.socket &&
-          sudo systemctl enable uda.socket &&
-          nc -4zv localhost 56565 &&
-          export UDA_HOST=localhost &&
-          export UDA_PORT=56565 &&
-          export UDA_CLIENT_SSL_AUTHENTICATE=1 &&
-          export UDA_CLIENT_CA_SSL_CERT=$PWD/rootCA.crt &&
-          export UDA_CLIENT_SSL_CERT=$PWD/client.crt &&
-          export UDA_CLIENT_SSL_KEY=$PWD/client.key &&
+        run: |
+          sudo cp /usr/local/etc/uda.socket /usr/local/etc/uda@.service /etc/systemd/system
+          sudo chown -R $USER:$USER /usr/local/etc
+          # pulls in extra config options from machine.d
+          echo "export UDAHOSTNAME=github-ci-ssl" >> /usr/local/etc/udaserver.cfg
+          ./scripts/create_certs.sh
+          mkdir /usr/local/etc/certs
+          cp rootCA.crt server.crt server.key /usr/local/etc/certs
+          sudo systemctl start uda.socket
+          sudo systemctl enable uda.socket
+          nc -4zv localhost 56565
+          export UDA_HOST=localhost
+          export UDA_PORT=56565
+          export UDA_CLIENT_SSL_AUTHENTICATE=OFF
+          export UDA_CLIENT_CA_SSL_CERT=$PWD/rootCA.crt
+          export UDA_CLIENT_SSL_CERT=$PWD/client.crt
+          export UDA_CLIENT_SSL_KEY=$PWD/client.key
+          set +e
+          /usr/local/bin/uda_cli --request "help::help()" && exit 1 || echo "process failed successfully"
+          set -e
+          export UDA_CLIENT_SSL_AUTHENTICATE=ON
           ./build/test/plugins/plugin_test_testplugin
 
 #      - name: Test
