adding tests for uda_env_options and checking in CI that SSL env var updates work as expected

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -215,25 +215,32 @@ jobs:
           export UDA_HOST=localhost &&
           export UDA_PORT=56565 &&
           ./build/test/plugins/plugin_test_testplugin
+          ctest -V --test-dir build/test/unit_tests --output-on-failure
 
       - name: Run SSL system tests
         if: matrix.os == 'ubuntu-22.04' && matrix.ssl == 'ON'
-        run: >
-          sudo cp /usr/local/etc/uda.socket /usr/local/etc/uda@.service /etc/systemd/system &&
-          sudo chown -R $USER:$USER /usr/local/etc &&
-          echo "export UDAHOSTNAME=github-ci-ssl" >> /usr/local/etc/udaserver.cfg &&
-          ./scripts/create_certs.sh &&
-          mkdir /usr/local/etc/certs &&
-          cp rootCA.crt server.crt server.key /usr/local/etc/certs &&
-          sudo systemctl start uda.socket &&
-          sudo systemctl enable uda.socket &&
-          nc -4zv localhost 56565 &&
-          export UDA_HOST=localhost &&
-          export UDA_PORT=56565 &&
-          export UDA_CLIENT_SSL_AUTHENTICATE=1 &&
-          export UDA_CLIENT_CA_SSL_CERT=$PWD/rootCA.crt &&
-          export UDA_CLIENT_SSL_CERT=$PWD/client.crt &&
-          export UDA_CLIENT_SSL_KEY=$PWD/client.key &&
+        run: |
+          sudo cp /usr/local/etc/uda.socket /usr/local/etc/uda@.service /etc/systemd/system
+          sudo chown -R $USER:$USER /usr/local/etc
+          echo "export UDAHOSTNAME=github-ci-ssl" >> /usr/local/etc/udaserver.cfg
+          ./scripts/create_certs.sh
+          mkdir /usr/local/etc/certs
+          cp rootCA.crt server.crt server.key /usr/local/etc/certs
+          echo "export UDA_SERVER_SSL_AUTHENTICATE=ON" >> /usr/local/etc/udaserver.cfg
+          echo "export UDA_SERVER_SSL_CERT=/usr/local/etc/certs/server.crt" >> /usr/local/etc/udaserver.cfg
+          echo "export UDA_SERVER_SSL_KEY=/usr/local/etc/certs/server.key" >> /usr/local/etc/udaserver.cfg
+          echo "export UDA_SERVER_CA_SSL_CERT=/usr/local/etc/certs/rootCA.crt" >> /usr/local/etc/udaserver.cfg
+          sudo systemctl start uda.socket
+          sudo systemctl enable uda.socket
+          nc -4zv localhost 56565
+          export UDA_HOST=localhost
+          export UDA_PORT=56565
+          export UDA_CLIENT_SSL_AUTHENTICATE=OFF
+          export UDA_CLIENT_CA_SSL_CERT=$PWD/rootCA.crt
+          export UDA_CLIENT_SSL_CERT=$PWD/client.crt
+          export UDA_CLIENT_SSL_KEY=$PWD/client.key
+          ./build/test/plugins/plugin_test_testplugin && exit 1 || echo "failure expected"
+          export UDA_CLIENT_SSL_AUTHENTICATE=ON
           ./build/test/plugins/plugin_test_testplugin
 
 #      - name: Test
